global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'projecthub-monitor'
    environment: 'production'

rule_files:
  - '/etc/prometheus/alerts.yml'

scrape_configs:    
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          service: 'system'
          instance: 'ec2-instance'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'docker'
          instance: 'containers'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          service: 'database'
          instance: 'postgres'